### ISSUE TITLE
Unable to add new configuration option

### ISSUE THREAD

**Issue by IanDominey** [kanbandan/PredictiveCFD#3]
I'm trying to create a new configuration option but am being prompted with a password to change the "setup" part of the spreadsheet.  Is it possible to 'unprotect' that sheet in order to permit extra configuration to be added?

**Comment by kanbandan** [comment]
I locked that sheet down somewhat to protect people from overwriting stuff that breaks everything... Lets have a chat in person and I can give you the password so you can make your changes and then re-protect the sheet. ;-)
